spring:
  application:
    name: spring-boot-redis
  datasource:
    url: jdbc:postgresql://localhost:5432/card_service_db
    username: default
    password: default
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml
  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    com.example.demo: INFO
  structured:
    format:
      console: ecs

management:
  endpoint:
    info:
      enabled: true
    gateway:
      enabled: true
    health:
      show-components: always
      show-details: always
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8080